# Change these first
owner: claytonplong # Your GitHub organization or username, where this repository lives
repo: backup-uptime # The name of this repository

sites:
  - name: offsitedatasync.com
    url: https://www.offsitedatasync.com.com
  - name: keepitsafe
    url: https://www.keepitsafe.com/
  - name: livevault
    url: https://www.livevault.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.clong.us
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**B2B Upptime**"
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
